fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"
    profile_influxdb: "https://github.com/relybv/rely-profile_influxdb.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    influxdb: "https://github.com/n1tr0g/golja-influxdb.git"
    grafana: "https://github.com/voxpupuli/puppet-grafana.git"
    profile_telegraf: "https://github.com/relybv/rely-profile_telegraf.git"

  symlinks:
    role_monitor: "#{source_dir}"
