fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.13.1"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"
    profile_influxdb: "https://github.com/relybv/rely-profile_influxdb.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    influxdb: "https://github.com/n1tr0g/golja-influxdb.git"
    grafana: "https://github.com/voxpupuli/puppet-grafana.git"
    telegraf: "https://github.com/datacentred/puppet-telegraf.git"
    profile_telegraf: "https://github.com/relybv/rely-profile_telegraf.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"

  symlinks:
    role_monitor: "#{source_dir}"
