fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    java_ks: "https://github.com/puppetlabs/puppetlabs-java_ks.git"
    datacat: "https://github.com/richardc/puppet-datacat.git"
    profile_influxdb: "https://github.com/relybv/rely-profile_influxdb.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    profile_beats: "https://github.com/relybv/rely-profile_beats.git"
    profile_elasticsearch: "https://github.com/relybv/rely-profile_elasticsearch.git"
    profile_mcollective: "https://github.com/relybv/rely-profile_mcollective.git"
    profile_rundeck: "https://github.com/relybv/rely-profile_rundeck.git"
    zypprepo: "https://github.com/voxpupuli/puppet-zypprepo.git"
    elasticsearch: "https://github.com/elastic/puppet-elasticsearch.git"
    rabbitmq: "https://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    staging: "git://github.com/voxpupuli/puppet-staging.git"
    erlang: "git://github.com/garethr/garethr-erlang.git"
    yum: "https://github.com/CERIT-SC/puppet-yum.git"
    kibana: "https://github.com/elastic/puppet-kibana.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    influxdb: "https://github.com/n1tr0g/golja-influxdb.git"
    grafana: "https://github.com/voxpupuli/puppet-grafana.git"
    telegraf: "https://github.com/datacentred/puppet-telegraf.git"
    profile_telegraf: "https://github.com/relybv/rely-profile_telegraf.git"
    filebeat: "https://github.com/pcfens/puppet-filebeat.git"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      branch: "1.2.x"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"
    rundeck: "https://github.com/voxpupuli/puppet-rundeck.git"

  symlinks:
    role_monitor: "#{source_dir}"
